/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l476xx.h"
#include "reg_util.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClock_Setup(void);

int main(void)
{

	SystemClock_Setup();
    /* Loop forever */
	for(;;);
}

void SystemClock_Setup(void)
{
	RCC_TypeDef *pRCC = RCC;

//	REG_CLR_BIT(pRCC->PLLCFGR,12U);
	//1.Setting up main PLL (to max freq. 80MHz)
	//PLL_M = 1
	REG_SET_VAL(pRCC->PLLCFGR,0x01U,0x70U,4U);
	//PLL_N = 10
	REG_SET_VAL(pRCC->PLLCFGR,0x0AU,0x3FU,8U);
	//PLL_R = 2
	REG_SET_VAL(pRCC->PLLCFGR,0x02U,0x03U,25U);

	//PLL_REN (main PLL output enable )set
	REG_SET_VAL(pRCC->PLLCFGR,0x01U,0x01U,24U);



}
